import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Call.module.css'
import CallItem from '@/components/CallItem'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps()
{
   const req = await fetch('https://pokeapi.co/api/v2/pokemon/?limit=10');
   const pokemom = await req.json();

   pokemom.results.forEach((element,idx) => {
      element.id = idx +1,
      element.image = `https://unpkg.com/pokeapi-sprites@2.0.2/sprites/pokemon/other/dream-world/${element.id}.svg`,
      element.description = 'Há 10 minutos',
      element.icone = true
   });

   return {
    props: {pokemom}
   }
}


export default function Call({pokemom}) 
{

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className={styles.call_container}>

            <CallItem key={0} poke={{image: '/images/call.png', id:0,name:"Criar link da chamada", description:"Compartilhe um link para sua chamada do WhatsApp", icone: false}}/>

            <p className={styles.atualizacoes}>Recentes</p>

            {pokemom.results.map((it,idx) => <CallItem key={idx} poke={it}/>)}

          </div>
      </main>
    </>
  )
}
