import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Conversa from '@/components/Conversa'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps()
{
   const req = await fetch('https://pokeapi.co/api/v2/pokemon/?limit=13');
   const pokemom = await req.json();

   pokemom.results.forEach((element,idx) => {
      element.id = idx +1
   });

   return {
    props: {pokemom}
   }
}


export default function Home({pokemom}) 
{

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className={styles.conversa_container}>

            {pokemom.results.map((it,idx) => <Conversa key={idx} poke={it}/>)}

          </div>
      </main>
    </>
  )
}
